"""
Test suite for query tracking system.
Tests both standard tools and cypher subgraph integration.

TEST COVERAGE:
==============

Standard Tools (6 tools total):
--------------------------------
1. search_patients - test_search_patients_tool
   - Tests: Patient name search functionality
   - Expected routing: Direct tool call (matches specific_patient_keywords)
   - Cypher tracked: Patient search with CONTAINS clause

2. get_patient_procedures - test_get_patient_procedures_tool
   - Tests: Retrieval of patient procedures
   - Expected routing: Direct tool call (patient-specific query)
   - Cypher tracked: Patient->Encounter->Procedure relationship

3. get_patient_medications - test_get_patient_medications_tool
   - Tests: Retrieval of patient medications/drugs
   - Expected routing: Direct tool call (patient-specific query)
   - Cypher tracked: Patient->Encounter->Drug relationship

4. get_patient_conditions - test_get_patient_conditions_tool
   - Tests: Retrieval of patient conditions/diagnoses
   - Expected routing: Direct tool call (patient-specific query)
   - Cypher tracked: Patient->Encounter->Diagnosis relationship
   - Note: May use HAS_DIAGNOSIS instead of HAS_CONDITION based on actual schema

5. get_patient_encounters - test_get_patient_encounters_tool
   - Tests: Retrieval of patient encounters/visits
   - Expected routing: Direct tool call (patient-specific query)
   - Cypher tracked: Patient->Encounter relationship with labels

6. get_database_schema - test_get_database_schema_tool
   - Tests: Schema information retrieval
   - Expected routing: Direct tool call (matches "database schema" keyword)
   - Cypher tracked: None (returns static schema description)

Cypher Subgraph (2 tests):
---------------------------
7. cypher_subgraph (simple analytics) - test_cypher_subgraph_simple_analytics
   - Tests: Simple count aggregation
   - Expected routing: Cypher subgraph (no specific patient keywords)
   - Cypher tracked: Generated by DeepSeek model, executed by subgraph
   - Query type: COUNT aggregation

8. cypher_subgraph (complex analytics) - test_cypher_subgraph_complex_analytics
   - Tests: Complex aggregation with ordering and limiting
   - Expected routing: Cypher subgraph (analytics pattern)
   - Cypher tracked: Generated query with ORDER BY and LIMIT
   - Query type: Aggregation, grouping, and ranking

Response Quality Tests:
-----------------------
9. response_formatting - test_response_formatting_no_comprehensive_preamble
   - Tests: Summary agent response quality and directness
   - Expected routing: Cypher subgraph (analytics query)
   - Validates: NO "comprehensive" preambles, direct answers
   - Expected content: "Leonor133 Dicki44" and "$4,570,388.07"

QUERY TRACKING VERIFICATION:
============================
Each test verifies:
- Query is captured in executed_queries list
- Query source matches expected tool/subgraph
- Query contains valid Cypher syntax
- Parameters are tracked (for parameterized queries)
- Timestamp is recorded
- Total query count increases correctly

ROUTING LOGIC VERIFICATION:
===========================
- Tests 1-6: Should use standard tools (specific patient patterns)
- Tests 7-8: Should route to cypher subgraph (analytics patterns)
- Routing keywords tested:
  * "patient named" → standard tools
  * "database schema" → standard tools
  * "How many" → cypher subgraph
  * "most frequently" → cypher subgraph
"""
import sys
sys.path.append('..')

import pytest
from agent import create_agent, query_agent
import os
from dotenv import load_dotenv
from pathlib import Path

# Load environment variables from backend/.env
# Get the backend directory (parent of tests directory)
backend_dir = Path(__file__).parent.parent
env_path = backend_dir / '.env'
load_dotenv(env_path)


@pytest.fixture(scope="function")
def agent():
    """Create a fresh agent for each test to ensure complete isolation."""
    # Create a completely new agent instance for each test
    # This ensures no state accumulation between tests
    return create_agent()


@pytest.fixture(scope="function")
def conversation_state():
    """Initialize fresh conversation history and executed queries for each test."""
    # Return a new dict with fresh empty lists for each test
    # This ensures no conversation history or query accumulation between tests
    return {
        "history": [],
        "queries": []
    }

@pytest.mark.timeout(60)
def test_search_patients_tool(agent, conversation_state):
    """
    Test 1: search_patients tool
    Coverage: Standard tool for patient search
    Expected: Query with CONTAINS clause for name matching
    Routing: Matches "patient named" keyword → standard tools
    """
    print("\n" + "-" * 60)
    print("Test 1: search_patients Tool")
    print("-" * 60)

    question = "Search for patients named John"
    print(f"Question: {question}\n")

    response, conversation_state["history"], conversation_state["queries"] = query_agent(
        agent, question, conversation_state["history"], conversation_state["queries"]
    )

    print("Response (first 300 chars):")
    print(response[:300] + "..." if len(response) > 300 else response)
    print(f"\n✓ Queries executed: {len(conversation_state['queries'])}")

    assert len(conversation_state["queries"]) > 0, "No queries were executed"

    latest = conversation_state["queries"][-1]
    print(f"  Source: {latest['source']}")
    print(f"  Cypher: {latest['query'][:100]}...")

    assert "CONTAINS" in latest["query"].upper() or "search_patients" in latest["source"].lower()


@pytest.mark.timeout(60)
def test_get_patient_procedures_tool(agent, conversation_state):
    """
    Test 2: get_patient_procedures tool
    Coverage: Patient->Encounter->Procedure relationship
    Expected: Query traversing HAS_ENCOUNTER and HAS_PROCEDURE relationships
    Routing: Patient-specific query → standard tools
    """
    print("\n" + "-" * 60)
    print("Test 2: get_patient_procedures Tool")
    print("-" * 60)

    question = "What procedures has patient Ethan766 had?"
    print(f"Question: {question}\n")

    response, conversation_state["history"], conversation_state["queries"] = query_agent(
        agent, question, conversation_state["history"], conversation_state["queries"]
    )

    print("Response (first 400 chars):")
    print(response[:400] + "..." if len(response) > 400 else response)
    print(f"\n✓ Queries executed: {len(conversation_state['queries'])}")

    assert len(conversation_state["queries"]) > 0, "No queries were executed"

    latest = conversation_state["queries"][-1]
    print(f"\nLatest Query:")
    print(f"  Source: {latest['source']}")
    print(f"  Cypher: {latest['query'][:150]}...")


@pytest.mark.timeout(60)
def test_get_patient_medications_tool(agent, conversation_state):
    """
    Test 3: get_patient_medications tool
    Coverage: Patient->Encounter->Drug relationship
    Expected: Query traversing HAS_ENCOUNTER and HAS_DRUG relationships
    Routing: Patient-specific query → standard tools
    """
    print("\n" + "-" * 60)
    print("Test 3: get_patient_medications Tool")
    print("-" * 60)

    question = "What medications is Ethan766 taking?"
    print(f"Question: {question}\n")

    response, conversation_state["history"], conversation_state["queries"] = query_agent(
        agent, question, conversation_state["history"], conversation_state["queries"]
    )

    print("Response (first 400 chars):")
    print(response[:400] + "..." if len(response) > 400 else response)
    print(f"\n✓ Queries executed: {len(conversation_state['queries'])}")

    assert len(conversation_state["queries"]) > 0, "No queries were executed"

    # Assert that response should not mention "recent 30" when less than 30 results returned
    assert "recent 30" not in response.lower(), \
        "Response should not mention 'recent 30' when fewer than 30 results were returned"

    latest = conversation_state["queries"][-1]
    print(f"\nLatest Query:")
    print(f"  Source: {latest['source']}")


@pytest.mark.timeout(60)
def test_get_patient_conditions_tool(agent, conversation_state):
    """
    Test 4: get_patient_conditions tool
    Coverage: Patient->Encounter->Diagnosis relationship
    Expected: Query traversing HAS_ENCOUNTER and HAS_DIAGNOSIS relationships
    Routing: Patient-specific query → standard tools
    Note: Schema uses HAS_DIAGNOSIS, not HAS_CONDITION
    """
    print("\n" + "-" * 60)
    print("Test 4: get_patient_conditions Tool (Note: may use diagnoses instead)")
    print("-" * 60)

    question = "What diagnoses does Ethan766 have?"
    print(f"Question: {question}\n")

    response, conversation_state["history"], conversation_state["queries"] = query_agent(
        agent, question, conversation_state["history"], conversation_state["queries"]
    )

    print("Response (first 400 chars):")
    print(response[:400] + "..." if len(response) > 400 else response)
    print(f"\n✓ Queries executed: {len(conversation_state['queries'])}")

    assert len(conversation_state["queries"]) > 0, "No queries were executed"


@pytest.mark.timeout(60)
def test_get_patient_encounters_tool(agent, conversation_state):
    """
    Test 5: get_patient_encounters tool
    Coverage: Patient->Encounter relationship with encounter labels
    Expected: Query returning encounters with multi-label support (Emergency, Wellness, etc.)
    Routing: Patient-specific query → standard tools
    """
    print("\n" + "-" * 60)
    print("Test 5: get_patient_encounters Tool")
    print("-" * 60)

    question = "Show me all encounters for Ethan766"
    print(f"Question: {question}\n")

    response, conversation_state["history"], conversation_state["queries"] = query_agent(
        agent, question, conversation_state["history"], conversation_state["queries"]
    )

    print("Response (first 400 chars):")
    print(response[:400] + "..." if len(response) > 400 else response)
    print(f"\n✓ Queries executed: {len(conversation_state['queries'])}")

    assert len(conversation_state["queries"]) > 0, "No queries were executed"


@pytest.mark.timeout(60)
def test_get_database_schema_tool(agent, conversation_state):
    """
    Test 6: get_database_schema tool
    Coverage: Schema information retrieval (static, no Cypher execution)
    Expected: No query tracked (returns static description)
    Routing: Matches "database schema" keyword → standard tools
    """
    print("\n" + "-" * 60)
    print("Test 6: get_database_schema Tool")
    print("-" * 60)

    question = "What is the database schema?"
    print(f"Question: {question}\n")

    response, conversation_state["history"], conversation_state["queries"] = query_agent(
        agent, question, conversation_state["history"], conversation_state["queries"]
    )

    print("Response (first 300 chars):")
    print(response[:300] + "..." if len(response) > 300 else response)
    print(f"\n✓ Queries executed: {len(conversation_state['queries'])}")

    assert response is not None and len(response) > 0, "No response received"


@pytest.mark.timeout(60)
def test_cypher_subgraph_simple_analytics(agent, conversation_state):
    """
    Test 7: Cypher subgraph - simple count
    Coverage: Cypher subgraph with COUNT aggregation
    Expected: LLM-generated query with COUNT(p) pattern
    Routing: "How many" keyword → cypher subgraph (catch-all for analytics)
    """
    print("\n" + "-" * 60)
    print("Test 7: Cypher Subgraph - Simple Analytics")
    print("-" * 60)

    question = "How many patients are in the database?"
    print(f"Question: {question}\n")

    response, conversation_state["history"], conversation_state["queries"] = query_agent(
        agent, question, conversation_state["history"], conversation_state["queries"]
    )

    print("Response:")
    print(response)
    print(f"\n✓ Queries executed: {len(conversation_state['queries'])}")

    assert len(conversation_state["queries"]) > 0, "No queries were executed"

    latest = conversation_state["queries"][-1]
    print(f"\nLatest Query:")
    print(f"  Source: {latest['source']}")
    print(f"  Cypher: {latest['query'][:150]}...")
    if latest.get('question'):
        print(f"  Original Question: {latest['question']}")


@pytest.mark.timeout(60)
def test_cypher_subgraph_complex_analytics(agent, conversation_state):
    """
    Test 8: Cypher subgraph - complex analytics
    Coverage: Cypher subgraph with complex aggregation, grouping, and ranking
    Expected: LLM-generated query with GROUP BY, ORDER BY, LIMIT
    Routing: "most frequently" keyword → cypher subgraph (analytics pattern)
    """
    print("\n" + "-" * 60)
    print("Test 8: Cypher Subgraph - Complex Analytics")
    print("-" * 60)

    question = "Which procedures were performed most frequently? Show top 10."
    print(f"Question: {question}\n")

    response, conversation_state["history"], conversation_state["queries"] = query_agent(
        agent, question, conversation_state["history"], conversation_state["queries"]
    )

    print("Response (first 600 chars):")
    print(response[:600] + "..." if len(response) > 600 else response)
    print(f"\n✓ Queries executed: {len(conversation_state['queries'])}")

    assert len(conversation_state["queries"]) > 0, "No queries were executed"

    latest = conversation_state["queries"][-1]
    print(f"\nLatest Query:")
    print(f"  Source: {latest['source']}")
    print(f"  Cypher (first 200 chars): {latest['query'][:200]}...")


@pytest.mark.timeout(60)
def test_response_formatting_no_comprehensive_preamble(agent, conversation_state):
    """
    Test 9: Response formatting - No comprehensive preambles
    Coverage: Verify summary agent provides direct answers without verbose preambles
    Expected: Direct answer with patient name and amount, NO "comprehensive" phrase
    Routing: Analytics query → cypher subgraph

    This test ensures the summary agent:
    - Does NOT use "To provide a more comprehensive answer"
    - Contains expected data: "Leonor133 Dicki44" and "$4,570,388.07"
    - Formats single results as sentences, NOT bullet lists
    """
    print("\n" + "-" * 60)
    print("Test 9: Response Formatting - No Comprehensive Preamble")
    print("-" * 60)

    question = "Which patient has spent the most on treatments?"
    print(f"Question: {question}\n")

    response, conversation_state["history"], conversation_state["queries"] = query_agent(
        agent, question, conversation_state["history"], conversation_state["queries"]
    )

    print("Full Response:")
    print("-" * 60)
    print(response)
    print("-" * 60)

    # Check that response contains expected content
    assert "Leonor133 Dicki44" in response, \
        "Response should contain patient name 'Leonor133 Dicki44'"

    assert "$4,570,388.07" in response, \
        "Response should contain amount '$4,570,388.07'"

    # Check that response does NOT contain the preamble phrase
    assert "To provide a more comprehensive answer" not in response, \
        "Response should NOT contain 'To provide a more comprehensive answer'"

    print("\n✓ Test passed: Response is direct and concise")
    print(f"✓ Contains patient name: Leonor133 Dicki44")
    print(f"✓ Contains amount: $4,570,388.07")
    print(f"✓ Does NOT contain comprehensive preamble")

    # Verify at least one query was executed
    assert len(conversation_state["queries"]) > 0, "No queries were executed"
    print(f"✓ Queries executed: {len(conversation_state['queries'])}")
